# Unchanged upstream Rstruct.v checked with Rocq 9.1.1 / Stdlib 9.1.0.
# Extend the upstream Stdlib upper bound to include this tested version.
opam-version: "2.0"
name: "rocq-mathcomp-reals-stdlib"
version: "1.16.0"
synopsis:
  "A library to link real numbers from mathematical components and Stdlib"
description: """\
This package contains a library to link real numbers for
the Coq proof-assistant using the Mathematical Components library and Stdlib."""
maintainer: "Reynald Affeldt <reynald.affeldt@aist.go.jp>"
authors: [
  "Reynald Affeldt"
  "Alessandro Bruni"
  "Yves Bertot"
  "Cyril Cohen"
  "Marie Kerjean"
  "Assia Mahboubi"
  "Damien Rouhling"
  "Pierre Roux"
  "Kazuhiko Sakaguchi"
  "Zachary Stone"
  "Pierre-Yves Strub"
  "Laurent Théry"
]
license: "CECILL-C"
tags: [
  "category:Mathematics/Real Numbers"
  "keyword:real numbers"
  "keyword:reals"
  "logpath:mathcomp.reals_stdlib"
]
homepage: "https://github.com/math-comp/analysis"
bug-reports: "https://github.com/math-comp/analysis/issues"
depends: [
  ("coq" {< "8.21~"} | "rocq-stdlib" {(>= "9.0" & < "9.2~") | (= "dev")})
  "rocq-mathcomp-reals" {= version}
]
conflicts: [
  "coq-mathcomp-reals-stdlib" {< "1.16~"}
]
build: [make "-C" "reals_stdlib" "-j%{jobs}%"]
install: [make "-C" "reals_stdlib" "install"]
dev-repo: "git+https://github.com/math-comp/analysis.git"
url {
  src:
    "https://github.com/math-comp/analysis/releases/download/1.16.0/analysis-1.16.0.tar.gz"
  checksum:
    "sha256=85aceb6c53f8c659ccee73df15b80c7e466433b1e94b25588af2fd3bf01248f2"
}
