#!/usr/bin/env python3
"""Fit the Examples.v 2 -> 3 -> 1 sigmoid network; export PyTorch and Rocq parameters."""
import argparse
import copy
import json
import math
from pathlib import Path

import torch
from torch import nn


# Snapshot of Examples.addition_net100, checked with Rocq's vm_compute.
ROCQ_NET100 = {
    "w1": [[-1.14747, -1.65057], [1.65307, 1.11217], [-0.69453, -0.62955]],
    "b1": [0.84848, -0.84009, -0.24799],
    "w2": [-2.60862, 2.45107, -1.10451],
    "b2": -0.20947,
}


class AdditionNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(2, 3, dtype=torch.float64)
        self.output = nn.Linear(3, 1, dtype=torch.float64)

    def forward(self, inputs):
        return torch.sigmoid(self.output(torch.sigmoid(self.hidden(inputs))))

    def predict(self, inputs):
        return (self(inputs) - 0.1) / 0.4

    @torch.no_grad()
    def set_parameters(self, values):
        for destination, source in [
            (self.hidden.weight, values["w1"]),
            (self.hidden.bias, values["b1"]),
            (self.output.weight, [values["w2"]]),
            (self.output.bias, [values["b2"]]),
        ]:
            destination.copy_(torch.tensor(source, dtype=torch.float64))

    def export_parameters(self):
        return {
            "w1": self.hidden.weight.detach().tolist(),
            "b1": self.hidden.bias.detach().tolist(),
            "w2": self.output.weight.detach()[0].tolist(),
            "b2": self.output.bias.detach()[0].item(),
        }


def grid(size):
    axis = torch.linspace(0, 1, size, dtype=torch.float64)
    return torch.cartesian_prod(axis, axis)


def loss_for(net, inputs):
    target = 0.1 + 0.4 * inputs.sum(dim=1, keepdim=True)
    return 0.5 * (net(inputs) - target).square().mean()


@torch.no_grad()
def metrics(net, inputs):
    error = net.predict(inputs).flatten() - inputs.sum(dim=1)
    return {
        "encoded_half_mse": loss_for(net, inputs).item(),
        "sum_rmse": error.square().mean().sqrt().item(),
        "sum_mae": error.abs().mean().item(),
        "sum_max_absolute_error": error.abs().max().item(),
        "points": len(inputs),
    }


def train_candidate(seed, train_inputs, adam_steps, lbfgs_steps, warm_start=False):
    torch.manual_seed(seed)
    net = AdditionNet()
    if warm_start:
        net.set_parameters(ROCQ_NET100)
    best_loss = float("inf")
    best_state = None

    def remember(loss):
        nonlocal best_loss, best_state
        value = loss.detach().item()
        if math.isfinite(value) and value < best_loss:
            best_loss = value
            best_state = copy.deepcopy(net.state_dict())

    adam = torch.optim.Adam(net.parameters(), lr=0.03)
    for _ in range(adam_steps):
        adam.zero_grad()
        loss = loss_for(net, train_inputs)
        remember(loss)
        loss.backward()
        adam.step()
    remember(loss_for(net, train_inputs))
    net.load_state_dict(best_state)
    optimizer = torch.optim.LBFGS(
        net.parameters(), max_iter=lbfgs_steps, max_eval=lbfgs_steps * 2,
        tolerance_grad=1e-12, tolerance_change=1e-16,
        history_size=50, line_search_fn="strong_wolfe",
    )

    def closure():
        optimizer.zero_grad()
        loss = loss_for(net, train_inputs)
        remember(loss)
        loss.backward()
        return loss

    optimizer.step(closure)
    remember(loss_for(net, train_inputs))
    net.load_state_dict(best_state)
    return net, best_loss


def coq_definition(values):
    # Five decimal places match the executable Rocq trainer's parameter precision.
    def q(value):
        return f"{value:.5f}"

    def vector(values):
        return "[" + "; ".join(q(value) for value in values) + "]"

    matrix = "[" + "; ".join(vector(row) for row in values["w1"]) + "]"
    return f"""(* Generated by train_addition.py. Best observed fit, not a proof of optimality. *)
From Backprop Require Import Examples.
From Stdlib Require Import QArith List.
Import ListNotations.
Open Scope Q_scope.

Definition addition_pytorch : AdditionNet :=
  {{| w1 := {matrix};
     b1 := {vector(values['b1'])};
     w2 := {vector(values['w2'])};
     b2 := {q(values['b2'])} |}}.

(* Unrounded encoded half-MSE, to avoid hiding small losses with round5. *)
Eval vm_compute in Qred (addition_total_loss addition_pytorch addition_data / 25).
Eval vm_compute in addition_test addition_pytorch.
Eval vm_compute in addition_predict addition_pytorch 0.12 0.34.
Eval vm_compute in addition_predict addition_pytorch 0.7 0.15.
Eval vm_compute in addition_predict addition_pytorch 0.01 0.99.
Eval vm_compute in addition_predict addition_pytorch 0.456 0.123.
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--restarts", type=int, default=12,
                        help="Total candidates, including the Rocq checkpoint warm start")
    parser.add_argument("--adam-steps", type=int, default=1500)
    parser.add_argument("--lbfgs-steps", type=int, default=2000)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output-dir", type=Path,
                        default=Path(__file__).resolve().parent / "pytorch_results")
    args = parser.parse_args()
    if args.restarts < 1 or args.adam_steps < 0 or args.lbfgs_steps < 1:
        parser.error("Need restarts >= 1, adam-steps >= 0, lbfgs-steps >= 1")
    torch.set_num_threads(1)
    torch.use_deterministic_algorithms(True)
    train_inputs = grid(5)
    # Diagnostic only: never used for optimization or candidate selection.
    evaluation_inputs = grid(101)
    baseline = AdditionNet()
    baseline.set_parameters(ROCQ_NET100)
    candidates = []
    best_net, best_loss, best_index = None, float("inf"), None
    for index in range(args.restarts):
        net, loss = train_candidate(args.seed + index, train_inputs,
                                    args.adam_steps, args.lbfgs_steps, index == 0)
        candidates.append({"seed": args.seed + index, "warm_start": index == 0,
                           "encoded_half_mse": loss})
        print(f"Candidate {index + 1}/{args.restarts}: loss={loss:.12g}", flush=True)
        if loss < best_loss:
            best_net, best_loss, best_index = net, loss, index
    parameters = best_net.export_parameters()
    rounded = json.loads(json.dumps(parameters), parse_float=lambda x: round(float(x), 5))
    rounded_net = AdditionNet()
    rounded_net.set_parameters(rounded)
    examples = torch.tensor([[0.12, 0.34], [0.7, 0.15], [0.01, 0.99],
                             [0.456, 0.123], [0, 0], [1, 1]], dtype=torch.float64)
    report = {
        "torch_version": torch.__version__, "architecture": [2, 3, 1],
        "activation": "sigmoid in both layers", "dtype": "float64",
        "domain": "Each input in [0, 1]; predictions approximate x + y",
        "training": {"points": 25, "encoding": "0.1 + 0.4 * (x + y)",
                     "objective": "mean((output - encoded_target)^2) / 2",
                     "adam_steps": args.adam_steps, "adam_lr": 0.03,
                     "lbfgs_max_iter": args.lbfgs_steps, "seed": args.seed,
                     "restarts": args.restarts, "selected_candidate": best_index,
                     "selection": "lowest training loss; no global optimum guarantee"},
        "parameters": parameters, "parameters_5dp": rounded,
        "baseline_rocq_net100_parameters": ROCQ_NET100,
        "baseline_float_sigmoid": {"train": metrics(baseline, train_inputs),
                                   "grid_101": metrics(baseline, evaluation_inputs)},
        "best_float_sigmoid": {"train": metrics(best_net, train_inputs),
                               "grid_101": metrics(best_net, evaluation_inputs)},
        "rounded_parameters_float_sigmoid": {
            "train": metrics(rounded_net, train_inputs),
            "grid_101": metrics(rounded_net, evaluation_inputs)},
        "examples": [{"input": xy.tolist(), "expected": xy.sum().item(),
                      "prediction": pred.item()}
                     for xy, pred in zip(examples, best_net.predict(examples).detach())],
        "candidates": candidates,
        "arithmetic_note": "PyTorch uses float64 sigmoid without intermediate rounding. "
                           "BestParameters.v uses Rocq's rational Taylor sigmoid and round5. "
                           "The 101x101 grid is a diagnostic, not a bound on the whole domain.",
    }
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "results.json").write_text(json.dumps(report, indent=2) + "\n")
    torch.save(best_net.state_dict(), args.output_dir / "addition_state_dict.pt")
    (args.output_dir / "BestParameters.v").write_text(coq_definition(rounded))
    print(json.dumps({"parameters_5dp": rounded,
                      "best_float_sigmoid": report["best_float_sigmoid"],
                      "examples": report["examples"]}, indent=2))
    print(f"Saved results to {args.output_dir}")


if __name__ == "__main__":
    main()
